# 기지전쟁 플러그인 설정 파일

# 사용될 팀 목록을 정의합니다.
teams:
  RED:
  BLUE:
  YELLOW:
  GREEN:

# 게임 시작 후 무적 시간 (초 단위)
invincibility-duration: 900

# 신호기 설치 가능 범위 제한 (좌표)
beacon-placement-restrictions:
  enabled: true
  min-x: -1000
  max-x: 1000
  min-y: 0
  max-y: 256
  min-z: -1000
  max-z: 1000