name: BaseWar
version: 1.0.0
main: com.example.basewar.BaseWarPlugin
api-version: '1.21'
author: Gemini
commands:
  bw:
    description: 기지전쟁 게임을 관리합니다.
    usage: /bw <start|stop>
    permission: basewar.admin
  join:
    description: 원하는 팀에 참여합니다.
    usage: /join <team>
